class M_Excecao(Exception):
    pass

try:
    x = int(input("Digite um nÃºmero positivo: "))
    if x > 0:
        print('digite um numero ppositivo')

finally :
    print('finalizou')